apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: app-scenario-stack
  namespace: app-scenario
spec:
  logLevel: info
  retention: 1d
  resourceSelector:
    matchLabels:
      monitoring.rhobs/stack: app-scenario
  namespaceSelector:
    matchNames:
      - app-scenario
  prometheusConfig:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  alertmanagerConfig:
    disabled: false
