apiVersion: v1
kind: Namespace
metadata:
  name: app-scenario
  labels:
    # Required by NetworkPolicy selectors and MonitoringStack namespaceSelector
    kubernetes.io/metadata.name: app-scenario
    monitoring.rhobs/stack: app-scenario
