---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: app-scenario
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend
  namespace: app-scenario
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mock-db
  namespace: app-scenario
